package vn.com.daisy.user;
// Generated Oct 16, 2015 10:39:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserInfo generated by hbm2java
 */
@Entity
@Table(name="UserInfo"
    ,catalog="HealthInformationSystem"
)
public class UserInfo  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -5580160222324808982L;
	private int userInfoId;
     private String surName;
     private String firstName;
     private String email;
     private String phoneNumber;
     private String jobTitle;
     private String introduction;
     private String gender;
     private Date birthday;
     private String nationality;
     private String employer;
     private String education;
     private String interest;
     private String languages;
     private Integer organisationUnitId;
     private String uid;
     private String code;
     private Date lastUpdated;
     private Date lastCheckedInterpretations;
     private Date created;
     private Boolean disabled;

    public UserInfo() {
    }

	
    public UserInfo(int userInfoId, String surName, String firstName) {
        this.userInfoId = userInfoId;
        this.surName = surName;
        this.firstName = firstName;
    }
    public UserInfo(int userInfoId, String surName, String firstName, String email, String phoneNumber, String jobTitle, String introduction, String gender, Date birthday, String nationality, String employer, String education, String interest, String languages, Integer organisationUnitId, String uid, String code, Date lastUpdated, Date lastCheckedInterpretations, Date created, Boolean disabled) {
       this.userInfoId = userInfoId;
       this.surName = surName;
       this.firstName = firstName;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.jobTitle = jobTitle;
       this.introduction = introduction;
       this.gender = gender;
       this.birthday = birthday;
       this.nationality = nationality;
       this.employer = employer;
       this.education = education;
       this.interest = interest;
       this.languages = languages;
       this.organisationUnitId = organisationUnitId;
       this.uid = uid;
       this.code = code;
       this.lastUpdated = lastUpdated;
       this.lastCheckedInterpretations = lastCheckedInterpretations;
       this.created = created;
       this.disabled = disabled;
    }
   
     @Id 

    
    @Column(name="UserInfoID", unique=true, nullable=false)
    public int getUserInfoId() {
        return this.userInfoId;
    }
    
    public void setUserInfoId(int userInfoId) {
        this.userInfoId = userInfoId;
    }

    
    @Column(name="SurName", nullable=false, length=160)
    public String getSurName() {
        return this.surName;
    }
    
    public void setSurName(String surName) {
        this.surName = surName;
    }

    
    @Column(name="FirstName", nullable=false, length=160)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="Email", length=160)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="PhoneNumber", length=20)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="JobTitle", length=160)
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    
    @Column(name="Introduction", length=160)
    public String getIntroduction() {
        return this.introduction;
    }
    
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    
    @Column(name="Gender", length=80)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Birthday", length=19)
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="Nationality", length=60)
    public String getNationality() {
        return this.nationality;
    }
    
    public void setNationality(String nationality) {
        this.nationality = nationality;
    }

    
    @Column(name="Employer", length=160)
    public String getEmployer() {
        return this.employer;
    }
    
    public void setEmployer(String employer) {
        this.employer = employer;
    }

    
    @Column(name="Education", length=65535)
    public String getEducation() {
        return this.education;
    }
    
    public void setEducation(String education) {
        this.education = education;
    }

    
    @Column(name="Interest", length=65535)
    public String getInterest() {
        return this.interest;
    }
    
    public void setInterest(String interest) {
        this.interest = interest;
    }

    
    @Column(name="Languages", length=65535)
    public String getLanguages() {
        return this.languages;
    }
    
    public void setLanguages(String languages) {
        this.languages = languages;
    }

    
    @Column(name="OrganisationUnitID")
    public Integer getOrganisationUnitId() {
        return this.organisationUnitId;
    }
    
    public void setOrganisationUnitId(Integer organisationUnitId) {
        this.organisationUnitId = organisationUnitId;
    }

    
    @Column(name="UID", length=11)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }

    
    @Column(name="Code", length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdated", length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastCheckedInterpretations", length=19)
    public Date getLastCheckedInterpretations() {
        return this.lastCheckedInterpretations;
    }
    
    public void setLastCheckedInterpretations(Date lastCheckedInterpretations) {
        this.lastCheckedInterpretations = lastCheckedInterpretations;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="Disabled")
    public Boolean getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }




}


