package vn.com.daisy.user;
// Generated Oct 16, 2015 10:39:47 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="User"
    ,catalog="HealthInformationSystem"
)
public class User  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 3018820760301485457L;
	private int userId;
     private String userName;
     private String password;
     private Date lastLogin;
     private Date passwordLastUpdated;
     private String restoreToken;
     private String restoreCode;
     private Date restoreExpiry;
     private Boolean selfRegistered;
     private Boolean disabled;

    public User() {
    }

	
    public User(int userId, String userName) {
        this.userId = userId;
        this.userName = userName;
    }
    public User(int userId, String userName, String password, Date lastLogin, Date passwordLastUpdated, String restoreToken, String restoreCode, Date restoreExpiry, Boolean selfRegistered, Boolean disabled) {
       this.userId = userId;
       this.userName = userName;
       this.password = password;
       this.lastLogin = lastLogin;
       this.passwordLastUpdated = passwordLastUpdated;
       this.restoreToken = restoreToken;
       this.restoreCode = restoreCode;
       this.restoreExpiry = restoreExpiry;
       this.selfRegistered = selfRegistered;
       this.disabled = disabled;
    }
   
     @Id 

    
    @Column(name="UserID", unique=true, nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }

    
    @Column(name="UserName", nullable=false)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="Password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastLogin", length=19)
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PasswordLastUpdated", length=19)
    public Date getPasswordLastUpdated() {
        return this.passwordLastUpdated;
    }
    
    public void setPasswordLastUpdated(Date passwordLastUpdated) {
        this.passwordLastUpdated = passwordLastUpdated;
    }

    
    @Column(name="RestoreToken")
    public String getRestoreToken() {
        return this.restoreToken;
    }
    
    public void setRestoreToken(String restoreToken) {
        this.restoreToken = restoreToken;
    }

    
    @Column(name="RestoreCode")
    public String getRestoreCode() {
        return this.restoreCode;
    }
    
    public void setRestoreCode(String restoreCode) {
        this.restoreCode = restoreCode;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RestoreExpiry", length=19)
    public Date getRestoreExpiry() {
        return this.restoreExpiry;
    }
    
    public void setRestoreExpiry(Date restoreExpiry) {
        this.restoreExpiry = restoreExpiry;
    }

    
    @Column(name="SelfRegistered")
    public Boolean getSelfRegistered() {
        return this.selfRegistered;
    }
    
    public void setSelfRegistered(Boolean selfRegistered) {
        this.selfRegistered = selfRegistered;
    }

    
    @Column(name="Disabled")
    public Boolean getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }




}


