package vn.com.daisy.user;
// Generated Oct 16, 2015 10:39:47 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UserMembershipId generated by hbm2java
 */
@Embeddable
public class UserMembershipId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 6920841121356092050L;
	private int organisationUnitId;
     private int userRoleId;

    public UserMembershipId() {
    }

    public UserMembershipId(int organisationUnitId, int userRoleId) {
       this.organisationUnitId = organisationUnitId;
       this.userRoleId = userRoleId;
    }
   


    @Column(name="OrganisationUnitID", nullable=false)
    public int getOrganisationUnitId() {
        return this.organisationUnitId;
    }
    
    public void setOrganisationUnitId(int organisationUnitId) {
        this.organisationUnitId = organisationUnitId;
    }


    @Column(name="UserRoleID", nullable=false)
    public int getUserRoleId() {
        return this.userRoleId;
    }
    
    public void setUserRoleId(int userRoleId) {
        this.userRoleId = userRoleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserMembershipId) ) return false;
		 UserMembershipId castOther = ( UserMembershipId ) other; 
         
		 return (this.getOrganisationUnitId()==castOther.getOrganisationUnitId())
 && (this.getUserRoleId()==castOther.getUserRoleId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrganisationUnitId();
         result = 37 * result + this.getUserRoleId();
         return result;
   }   


}


