package vn.com.daisy.dataelement;
// Generated Nov 20, 2015 12:54:09 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoryCategoryOptionId generated by hbm2java
 */
@Embeddable
public class CategoryCategoryOptionId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1802016451289564220L;
	private int categoryId;
     private int sortOrder;

    public CategoryCategoryOptionId() {
    }

    public CategoryCategoryOptionId(int categoryId, int sortOrder) {
       this.categoryId = categoryId;
       this.sortOrder = sortOrder;
    }
   


    @Column(name="CategoryID", nullable=false)
    public int getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }


    @Column(name="Sort_Order", nullable=false)
    public int getSortOrder() {
        return this.sortOrder;
    }
    
    public void setSortOrder(int sortOrder) {
        this.sortOrder = sortOrder;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CategoryCategoryOptionId) ) return false;
		 CategoryCategoryOptionId castOther = ( CategoryCategoryOptionId ) other; 
         
		 return (this.getCategoryId()==castOther.getCategoryId())
 && (this.getSortOrder()==castOther.getSortOrder());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCategoryId();
         result = 37 * result + this.getSortOrder();
         return result;
   }   


}


