package vn.com.daisy.dataelement;
// Generated Nov 20, 2015 12:54:09 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DataElementCategoryOptionsId generated by hbm2java
 */
@Embeddable
public class DataElementCategoryOptionsId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1365770622539940959L;
	private int dataElementId;
     private int categoryOptionId;

    public DataElementCategoryOptionsId() {
    }

    public DataElementCategoryOptionsId(int dataElementId, int categoryOptionId) {
       this.dataElementId = dataElementId;
       this.categoryOptionId = categoryOptionId;
    }
   


    @Column(name="DataElementID", nullable=false)
    public int getDataElementId() {
        return this.dataElementId;
    }
    
    public void setDataElementId(int dataElementId) {
        this.dataElementId = dataElementId;
    }


    @Column(name="CategoryOptionID", nullable=false)
    public int getCategoryOptionId() {
        return this.categoryOptionId;
    }
    
    public void setCategoryOptionId(int categoryOptionId) {
        this.categoryOptionId = categoryOptionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DataElementCategoryOptionsId) ) return false;
		 DataElementCategoryOptionsId castOther = ( DataElementCategoryOptionsId ) other; 
         
		 return (this.getDataElementId()==castOther.getDataElementId())
 && (this.getCategoryOptionId()==castOther.getCategoryOptionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDataElementId();
         result = 37 * result + this.getCategoryOptionId();
         return result;
   }   


}


