package vn.com.daisy.dataelement;
// Generated Nov 20, 2015 12:54:09 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataElementCategoryOption generated by hbm2java
 */
@Entity
@Table(name="DataElementCategoryOption"
    ,catalog="HealthInformationSystem"
)
public class DataElementCategoryOption  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 2842879879235497488L;
	private int categoryOptionId;
     private String shortName;
     private String name;
     private String uid;
     private String code;
     private Date lastUpdated;
     private Date created;
     private Integer userId;
     private String publicAccess;

    public DataElementCategoryOption() {
    }

	
    public DataElementCategoryOption(int categoryOptionId, String shortName, String name) {
        this.categoryOptionId = categoryOptionId;
        this.shortName = shortName;
        this.name = name;
    }
    public DataElementCategoryOption(int categoryOptionId, String shortName, String name, String uid, String code, Date lastUpdated, Date created, Integer userId, String publicAccess) {
       this.categoryOptionId = categoryOptionId;
       this.shortName = shortName;
       this.name = name;
       this.uid = uid;
       this.code = code;
       this.lastUpdated = lastUpdated;
       this.created = created;
       this.userId = userId;
       this.publicAccess = publicAccess;
    }
   
     @Id 

    
    @Column(name="CategoryOptionID", unique=true, nullable=false)
    public int getCategoryOptionId() {
        return this.categoryOptionId;
    }
    
    public void setCategoryOptionId(int categoryOptionId) {
        this.categoryOptionId = categoryOptionId;
    }

    
    @Column(name="ShortName", nullable=false, length=50)
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    
    @Column(name="Name", nullable=false, length=160)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="UID", length=11)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }

    
    @Column(name="Code", length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdated", length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="UserID")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="PublicAccess", length=8)
    public String getPublicAccess() {
        return this.publicAccess;
    }
    
    public void setPublicAccess(String publicAccess) {
        this.publicAccess = publicAccess;
    }




}


