package vn.com.daisy.dataelement;
// Generated Nov 20, 2015 12:54:09 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataElement generated by hbm2java
 */
@Entity
@Table(name="DataElement"
    ,catalog="HealthInformationSystem"
)
public class DataElement  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 8271621564335491333L;
	private int dataElementId;
     private String code;
     private String shortName;
     private String name;
     private String description;
     private String comment;
     private String uid;
     private String url;
     private String valueType;
     private String aggregationType;
     private String textType;
     private String numberType;
     private Boolean zeroIsSignificant;
     private Date lastUpdated;
     private Date created;
     private Integer userId;
     private String publicAccess;
     private Boolean disabled;

    public DataElement() {
    }

	
    public DataElement(int dataElementId, String shortName, String name, String valueType, String aggregationType) {
        this.dataElementId = dataElementId;
        this.shortName = shortName;
        this.name = name;
        this.valueType = valueType;
        this.aggregationType = aggregationType;
    }
    public DataElement(int dataElementId, String code, String shortName, String name, String description, String comment, String uid, String url, String valueType, String aggregationType, String textType, String numberType, Boolean zeroIsSignificant, Date lastUpdated, Date created, Integer userId, String publicAccess, Boolean disabled) {
       this.dataElementId = dataElementId;
       this.code = code;
       this.shortName = shortName;
       this.name = name;
       this.description = description;
       this.comment = comment;
       this.uid = uid;
       this.url = url;
       this.valueType = valueType;
       this.aggregationType = aggregationType;
       this.textType = textType;
       this.numberType = numberType;
       this.zeroIsSignificant = zeroIsSignificant;
       this.lastUpdated = lastUpdated;
       this.created = created;
       this.userId = userId;
       this.publicAccess = publicAccess;
       this.disabled = disabled;
    }
   
     @Id 

    
    @Column(name="DataElementID", unique=true, nullable=false)
    public int getDataElementId() {
        return this.dataElementId;
    }
    
    public void setDataElementId(int dataElementId) {
        this.dataElementId = dataElementId;
    }

    
    @Column(name="Code", length=100)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="ShortName", nullable=false, length=50)
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    
    @Column(name="Name", nullable=false, length=160)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Comment", length=65535)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="UID", length=11)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }

    
    @Column(name="URL")
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="ValueType", nullable=false, length=16)
    public String getValueType() {
        return this.valueType;
    }
    
    public void setValueType(String valueType) {
        this.valueType = valueType;
    }

    
    @Column(name="AggregationType", nullable=false, length=16)
    public String getAggregationType() {
        return this.aggregationType;
    }
    
    public void setAggregationType(String aggregationType) {
        this.aggregationType = aggregationType;
    }

    
    @Column(name="TextType", length=16)
    public String getTextType() {
        return this.textType;
    }
    
    public void setTextType(String textType) {
        this.textType = textType;
    }

    
    @Column(name="NumberType", length=16)
    public String getNumberType() {
        return this.numberType;
    }
    
    public void setNumberType(String numberType) {
        this.numberType = numberType;
    }

    
    @Column(name="ZeroIsSignificant")
    public Boolean getZeroIsSignificant() {
        return this.zeroIsSignificant;
    }
    
    public void setZeroIsSignificant(Boolean zeroIsSignificant) {
        this.zeroIsSignificant = zeroIsSignificant;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdated", length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="UserID")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="PublicAccess", length=8)
    public String getPublicAccess() {
        return this.publicAccess;
    }
    
    public void setPublicAccess(String publicAccess) {
        this.publicAccess = publicAccess;
    }

    
    @Column(name="Disabled")
    public Boolean getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }




}


