package vn.com.daisy.dataelement;
// Generated Nov 20, 2015 12:54:09 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * DataElementCategoryOptions generated by hbm2java
 */
@Entity
@Table(name="DataElement_CategoryOptions"
    ,catalog="HealthInformationSystem"
)
public class DataElementCategoryOptions  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1484112264813976990L;
	private DataElementCategoryOptionsId id;

    public DataElementCategoryOptions() {
    }

    public DataElementCategoryOptions(DataElementCategoryOptionsId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="dataElementId", column=@Column(name="DataElementID", nullable=false) ), 
        @AttributeOverride(name="categoryOptionId", column=@Column(name="CategoryOptionID", nullable=false) ) } )
    public DataElementCategoryOptionsId getId() {
        return this.id;
    }
    
    public void setId(DataElementCategoryOptionsId id) {
        this.id = id;
    }




}


