package vn.com.daisy.Period;
// Generated Oct 16, 2015 10:05:36 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;

import javax.persistence.Id;

import javax.persistence.Table;

/**
 * PeriodType generated by hbm2java
 */
@Entity
@Table(name = "PeriodType", catalog = "HealthInformationSystem")
public class PeriodType implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 3527417687545293403L;
	private int periodTypeId;
	private String name;

	public PeriodType() {
	}

	public PeriodType(int periodTypeId) {
		this.periodTypeId = periodTypeId;
	}

	public PeriodType(int periodTypeId, String name) {
		this.periodTypeId = periodTypeId;
		this.name = name;
	}

	@Id

	@Column(name = "PeriodTypeID", unique = true, nullable = false)
	public int getPeriodTypeId() {
		return this.periodTypeId;
	}

	public void setPeriodTypeId(int periodTypeId) {
		this.periodTypeId = periodTypeId;
	}

	@Column(name = "Name", length = 15)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
