package vn.com.daisy.Period;
// Generated Oct 16, 2015 10:05:36 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PeriodStructure generated by hbm2java
 */
@Entity
@Table(name="PeriodStructure"
    ,catalog="HealthInformationSystem"
)
public class PeriodStructure  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 6517834940437216273L;
	private int periodId;
     private String iso;
     private int daySno;
     private String daily;
     private String weekly;
     private String monthly;
     private String biMonthly;
     private String quartly;
     private String sixMonthly;
     private String sixMonthlyApril;
     private String yearly;
     private String finacialApril;
     private String financialJuly;
     private String financialOct;

    public PeriodStructure() {
    }

	
    public PeriodStructure(int periodId, String iso, int daySno) {
        this.periodId = periodId;
        this.iso = iso;
        this.daySno = daySno;
    }
    public PeriodStructure(int periodId, String iso, int daySno, String daily, String weekly, String monthly, String biMonthly, String quartly, String sixMonthly, String sixMonthlyApril, String yearly, String finacialApril, String financialJuly, String financialOct) {
       this.periodId = periodId;
       this.iso = iso;
       this.daySno = daySno;
       this.daily = daily;
       this.weekly = weekly;
       this.monthly = monthly;
       this.biMonthly = biMonthly;
       this.quartly = quartly;
       this.sixMonthly = sixMonthly;
       this.sixMonthlyApril = sixMonthlyApril;
       this.yearly = yearly;
       this.finacialApril = finacialApril;
       this.financialJuly = financialJuly;
       this.financialOct = financialOct;
    }
   
     @Id 

    
    @Column(name="PeriodID", unique=true, nullable=false)
    public int getPeriodId() {
        return this.periodId;
    }
    
    public void setPeriodId(int periodId) {
        this.periodId = periodId;
    }

    
    @Column(name="ISO", nullable=false, length=15)
    public String getIso() {
        return this.iso;
    }
    
    public void setIso(String iso) {
        this.iso = iso;
    }

    
    @Column(name="DaySNO", nullable=false)
    public int getDaySno() {
        return this.daySno;
    }
    
    public void setDaySno(int daySno) {
        this.daySno = daySno;
    }

    
    @Column(name="Daily", length=15)
    public String getDaily() {
        return this.daily;
    }
    
    public void setDaily(String daily) {
        this.daily = daily;
    }

    
    @Column(name="Weekly", length=15)
    public String getWeekly() {
        return this.weekly;
    }
    
    public void setWeekly(String weekly) {
        this.weekly = weekly;
    }

    
    @Column(name="Monthly", length=15)
    public String getMonthly() {
        return this.monthly;
    }
    
    public void setMonthly(String monthly) {
        this.monthly = monthly;
    }

    
    @Column(name="BiMonthly", length=15)
    public String getBiMonthly() {
        return this.biMonthly;
    }
    
    public void setBiMonthly(String biMonthly) {
        this.biMonthly = biMonthly;
    }

    
    @Column(name="Quartly", length=15)
    public String getQuartly() {
        return this.quartly;
    }
    
    public void setQuartly(String quartly) {
        this.quartly = quartly;
    }

    
    @Column(name="SixMonthly", length=15)
    public String getSixMonthly() {
        return this.sixMonthly;
    }
    
    public void setSixMonthly(String sixMonthly) {
        this.sixMonthly = sixMonthly;
    }

    
    @Column(name="SixMonthlyApril", length=15)
    public String getSixMonthlyApril() {
        return this.sixMonthlyApril;
    }
    
    public void setSixMonthlyApril(String sixMonthlyApril) {
        this.sixMonthlyApril = sixMonthlyApril;
    }

    
    @Column(name="Yearly", length=15)
    public String getYearly() {
        return this.yearly;
    }
    
    public void setYearly(String yearly) {
        this.yearly = yearly;
    }

    
    @Column(name="FinacialApril", length=15)
    public String getFinacialApril() {
        return this.finacialApril;
    }
    
    public void setFinacialApril(String finacialApril) {
        this.finacialApril = finacialApril;
    }

    
    @Column(name="FinancialJuly", length=15)
    public String getFinancialJuly() {
        return this.financialJuly;
    }
    
    public void setFinancialJuly(String financialJuly) {
        this.financialJuly = financialJuly;
    }

    
    @Column(name="FinancialOct", length=45)
    public String getFinancialOct() {
        return this.financialOct;
    }
    
    public void setFinancialOct(String financialOct) {
        this.financialOct = financialOct;
    }




}


