--------------------------------------------------------
--  File created - Saturday-September-10-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BVL_BILL
--------------------------------------------------------

  CREATE TABLE "BVL_BILL" ("BBI_ID" NUMBER(*,0), "BBI_COMPANY_CODE" VARCHAR2(9), "BBI_OUTLET_NUMBER" VARCHAR2(10), "BBI_INVOICE_NUMBER" VARCHAR2(20), "BBI_INVOICE_AMOUNT" NUMBER(12,0), "BBI_ACCOUNT_NUMBER" VARCHAR2(14), "BBI_POLICYHOLDER" VARCHAR2(100), "BBI_FROM_DATE" DATE, "BBI_TO_DATE" DATE, "BBI_BARCODE" VARCHAR2(13), "BBI_DATA_SOURCE" VARCHAR2(2), "BBI_INVOICE_TYPE" VARCHAR2(2), "BBI_CHANNEL_FREE_REGISTER" VARCHAR2(2), "BBI_CHANNEL_FREE_PERFORM" VARCHAR2(2), "BBI_STATUS" VARCHAR2(2), "BBI_FEE_DATE" DATE, "BBI_EFFECTIVE_DATE" DATE, "BBI_TRANSACTION_OFFICE_CODE" VARCHAR2(20), "BBI_TRANSACTION_ID" VARCHAR2(20), "BBI_LAST_UPDATED_DATE" DATE, "BBI_LAST_UPDATED_USER" VARCHAR2(50), "BBI_BANK_ACCOUNT" VARCHAR2(30), "BBI_CIF_NUMBER" VARCHAR2(30), "BBI_REGISTER_FEE_DATE" DATE, "BBI_BANK_REGISTER" VARCHAR2(10), "BBI_BANK_PERFORM" VARCHAR2(10), "BBI_INVOICE_EDATE" DATE, "BBI_PAYMENT_INSTRUCTION" VARCHAR2(2), "BBI_PAYMENT_OUTLET" VARCHAR2(10), "ISCOLLECTED" NUMBER(1,0), "JOB_ID" NUMBER(*,0), "T24BRANCH_ID" NUMBER(*,0), "T24USER_ID" NUMBER(*,0))
--------------------------------------------------------
--  DDL for Index BVL_BILL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "BVL_BILL_PK" ON "BVL_BILL" ("BBI_INVOICE_NUMBER", "BBI_BARCODE")
--------------------------------------------------------
--  Constraints for Table BVL_BILL
--------------------------------------------------------

  ALTER TABLE "BVL_BILL" ADD CONSTRAINT "BVL_BILL_PK" PRIMARY KEY ("BBI_INVOICE_NUMBER", "BBI_BARCODE") USING INDEX  ENABLE
  ALTER TABLE "BVL_BILL" MODIFY ("BBI_BARCODE" NOT NULL ENABLE)
  ALTER TABLE "BVL_BILL" MODIFY ("BBI_INVOICE_AMOUNT" NOT NULL ENABLE)
  ALTER TABLE "BVL_BILL" MODIFY ("BBI_INVOICE_NUMBER" NOT NULL ENABLE)
  ALTER TABLE "BVL_BILL" MODIFY ("BBI_OUTLET_NUMBER" NOT NULL ENABLE)
  ALTER TABLE "BVL_BILL" MODIFY ("BBI_COMPANY_CODE" NOT NULL ENABLE)
  ALTER TABLE "BVL_BILL" MODIFY ("BBI_ID" NOT NULL ENABLE)
