package vn.com.daisy.organisation;
// Generated Oct 20, 2015 8:20:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrganisationUnit generated by hbm2java
 */
@Entity
@Table(name="OrganisationUnit"
    ,catalog="HealthInformationSystem"
)
public class OrganisationUnit  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -9098109909000416842L;
	private int organisationUnitId;
     private Integer parentId;
     private String code;
     private String shortName;
     private String name;
     private String comment;
     private String coordinate;
     private String latitude;
     private String longitude;
     private String featureType;
     private String url;
     private String type;
     private String contactPersion;
     private String address;
     private String email;
     private String phoneNumber;
     private String description;
     private String uid;
     private Date openingDate;
     private Date closedDate;
     private Date lastUpdated;
     private Date created;
     private String uuid;
     private Integer userId;
     private String disabled;

    public OrganisationUnit() {
    }

	
    public OrganisationUnit(int organisationUnitId, String name) {
        this.organisationUnitId = organisationUnitId;
        this.name = name;
    }
    public OrganisationUnit(int organisationUnitId, Integer parentId, String code, String shortName, String name, String comment, String coordinate, String latitude, String longitude, String featureType, String url, String type, String contactPersion, String address, String email, String phoneNumber, String description, String uid, Date openingDate, Date closedDate, Date lastUpdated, Date created, String uuid, Integer userId, String disabled) {
       this.organisationUnitId = organisationUnitId;
       this.parentId = parentId;
       this.code = code;
       this.shortName = shortName;
       this.name = name;
       this.comment = comment;
       this.coordinate = coordinate;
       this.latitude = latitude;
       this.longitude = longitude;
       this.featureType = featureType;
       this.url = url;
       this.type = type;
       this.contactPersion = contactPersion;
       this.address = address;
       this.email = email;
       this.phoneNumber = phoneNumber;
       this.description = description;
       this.uid = uid;
       this.openingDate = openingDate;
       this.closedDate = closedDate;
       this.lastUpdated = lastUpdated;
       this.created = created;
       this.uuid = uuid;
       this.userId = userId;
       this.disabled = disabled;
    }
   
     @Id 

    
    @Column(name="OrganisationUnitID", unique=true, nullable=false)
    public int getOrganisationUnitId() {
        return this.organisationUnitId;
    }
    
    public void setOrganisationUnitId(int organisationUnitId) {
        this.organisationUnitId = organisationUnitId;
    }

    
    @Column(name="ParentID")
    public Integer getParentId() {
        return this.parentId;
    }
    
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    
    @Column(name="Code", length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="ShortName", length=50)
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    
    @Column(name="Name", nullable=false, length=160)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Comment", length=65535)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="Coordinate", length=65535)
    public String getCoordinate() {
        return this.coordinate;
    }
    
    public void setCoordinate(String coordinate) {
        this.coordinate = coordinate;
    }

    
    @Column(name="Latitude")
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    
    @Column(name="Longitude")
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    
    @Column(name="FeatureType")
    public String getFeatureType() {
        return this.featureType;
    }
    
    public void setFeatureType(String featureType) {
        this.featureType = featureType;
    }

    
    @Column(name="URL")
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }

    
    @Column(name="Type")
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="ContactPersion")
    public String getContactPersion() {
        return this.contactPersion;
    }
    
    public void setContactPersion(String contactPersion) {
        this.contactPersion = contactPersion;
    }

    
    @Column(name="Address")
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="Email", length=150)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="PhoneNumber", length=150)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    
    @Column(name="Description", length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="UID", length=11)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OpeningDate", length=19)
    public Date getOpeningDate() {
        return this.openingDate;
    }
    
    public void setOpeningDate(Date openingDate) {
        this.openingDate = openingDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ClosedDate", length=19)
    public Date getClosedDate() {
        return this.closedDate;
    }
    
    public void setClosedDate(Date closedDate) {
        this.closedDate = closedDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdated", length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="UUID", length=36)
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    
    @Column(name="UserID")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="Disabled", length=45)
    public String getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(String disabled) {
        this.disabled = disabled;
    }




}


