package vn.com.daisy.organisation;
// Generated Nov 22, 2015 4:59:23 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrgUnitGroupMembers generated by hbm2java
 */
@Entity
@Table(name="OrgUnitGroupMembers"
    ,catalog="HealthInformationSystem"
)
public class OrgUnitGroupMembers  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 3488021952198178848L;
	private OrgUnitGroupMembersId id;

    public OrgUnitGroupMembers() {
    }

    public OrgUnitGroupMembers(OrgUnitGroupMembersId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orgUnitGroupId", column=@Column(name="OrgUnitGroupID", nullable=false) ), 
        @AttributeOverride(name="organisationUnitId", column=@Column(name="OrganisationUnitID", nullable=false) ) } )
    public OrgUnitGroupMembersId getId() {
        return this.id;
    }
    
    public void setId(OrgUnitGroupMembersId id) {
        this.id = id;
    }




}


