package vn.com.daisy.organisation;
// Generated Oct 20, 2015 8:20:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * OrgUnitStructure generated by hbm2java
 */
@Entity
@Table(name="OrgUnitStructure"
    ,catalog="HealthInformationSystem"
)
public class OrgUnitStructure  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 5839650365919820477L;
	private int organisationUnitId;
     private String organisationUnitUid;
     private Integer level;

    public OrgUnitStructure() {
    }

	
    public OrgUnitStructure(int organisationUnitId) {
        this.organisationUnitId = organisationUnitId;
    }
    public OrgUnitStructure(int organisationUnitId, String organisationUnitUid, Integer level) {
       this.organisationUnitId = organisationUnitId;
       this.organisationUnitUid = organisationUnitUid;
       this.level = level;
    }
   
     @Id 

    
    @Column(name="OrganisationUnitID", unique=true, nullable=false)
    public int getOrganisationUnitId() {
        return this.organisationUnitId;
    }
    
    public void setOrganisationUnitId(int organisationUnitId) {
        this.organisationUnitId = organisationUnitId;
    }

    
    @Column(name="OrganisationUnitUID", length=11)
    public String getOrganisationUnitUid() {
        return this.organisationUnitUid;
    }
    
    public void setOrganisationUnitUid(String organisationUnitUid) {
        this.organisationUnitUid = organisationUnitUid;
    }

    
    @Column(name="Level")
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }




}


