package vn.com.daisy.organisation;
// Generated Nov 22, 2015 4:59:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrgUnitGroupSet generated by hbm2java
 */
@Entity
@Table(name="OrgUnitGroupSet"
    ,catalog="HealthInformationSystem"
)
public class OrgUnitGroupSet  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1196206394062258439L;
	private int orgUnitGroupSetId;
     private String name;
     private String description;
     private Boolean compulsoty;
     private Boolean exclusive;
     private String uid;
     private String code;
     private Date lastUpdated;
     private Date created;
     private Boolean dataDimension;
     private Integer userId;
     private String publicAccess;
     private Boolean disabled;

    public OrgUnitGroupSet() {
    }

	
    public OrgUnitGroupSet(int orgUnitGroupSetId, String name) {
        this.orgUnitGroupSetId = orgUnitGroupSetId;
        this.name = name;
    }
    public OrgUnitGroupSet(int orgUnitGroupSetId, String name, String description, Boolean compulsoty, Boolean exclusive, String uid, String code, Date lastUpdated, Date created, Boolean dataDimension, Integer userId, String publicAccess, Boolean disabled) {
       this.orgUnitGroupSetId = orgUnitGroupSetId;
       this.name = name;
       this.description = description;
       this.compulsoty = compulsoty;
       this.exclusive = exclusive;
       this.uid = uid;
       this.code = code;
       this.lastUpdated = lastUpdated;
       this.created = created;
       this.dataDimension = dataDimension;
       this.userId = userId;
       this.publicAccess = publicAccess;
       this.disabled = disabled;
    }
   
     @Id 

    
    @Column(name="OrgUnitGroupSetID", unique=true, nullable=false)
    public int getOrgUnitGroupSetId() {
        return this.orgUnitGroupSetId;
    }
    
    public void setOrgUnitGroupSetId(int orgUnitGroupSetId) {
        this.orgUnitGroupSetId = orgUnitGroupSetId;
    }

    
    @Column(name="Name", nullable=false, length=160)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Compulsoty")
    public Boolean getCompulsoty() {
        return this.compulsoty;
    }
    
    public void setCompulsoty(Boolean compulsoty) {
        this.compulsoty = compulsoty;
    }

    
    @Column(name="Exclusive")
    public Boolean getExclusive() {
        return this.exclusive;
    }
    
    public void setExclusive(Boolean exclusive) {
        this.exclusive = exclusive;
    }

    
    @Column(name="UID", length=11)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }

    
    @Column(name="Code", length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdated", length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="DataDimension")
    public Boolean getDataDimension() {
        return this.dataDimension;
    }
    
    public void setDataDimension(Boolean dataDimension) {
        this.dataDimension = dataDimension;
    }

    
    @Column(name="UserID")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="PublicAccess", length=8)
    public String getPublicAccess() {
        return this.publicAccess;
    }
    
    public void setPublicAccess(String publicAccess) {
        this.publicAccess = publicAccess;
    }

    
    @Column(name="Disabled")
    public Boolean getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }




}


