package vn.com.daisy.organisation;
// Generated Nov 22, 2015 4:59:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrgUnitGroupSetMemberId generated by hbm2java
 */
@Embeddable
public class OrgUnitGroupSetMemberId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 2085021709678321441L;
	private int orgUnitGroupSetId;
     private int orgUnitGroupId;

    public OrgUnitGroupSetMemberId() {
    }

    public OrgUnitGroupSetMemberId(int orgUnitGroupSetId, int orgUnitGroupId) {
       this.orgUnitGroupSetId = orgUnitGroupSetId;
       this.orgUnitGroupId = orgUnitGroupId;
    }
   


    @Column(name="OrgUnitGroupSetID", nullable=false)
    public int getOrgUnitGroupSetId() {
        return this.orgUnitGroupSetId;
    }
    
    public void setOrgUnitGroupSetId(int orgUnitGroupSetId) {
        this.orgUnitGroupSetId = orgUnitGroupSetId;
    }


    @Column(name="OrgUnitGroupID", nullable=false)
    public int getOrgUnitGroupId() {
        return this.orgUnitGroupId;
    }
    
    public void setOrgUnitGroupId(int orgUnitGroupId) {
        this.orgUnitGroupId = orgUnitGroupId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrgUnitGroupSetMemberId) ) return false;
		 OrgUnitGroupSetMemberId castOther = ( OrgUnitGroupSetMemberId ) other; 
         
		 return (this.getOrgUnitGroupSetId()==castOther.getOrgUnitGroupSetId())
 && (this.getOrgUnitGroupId()==castOther.getOrgUnitGroupId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrgUnitGroupSetId();
         result = 37 * result + this.getOrgUnitGroupId();
         return result;
   }   


}


