package vn.com.daisy.organisation;
// Generated Nov 22, 2015 4:59:23 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrgUnitGroup generated by hbm2java
 */
@Entity
@Table(name="OrgUnitGroup"
    ,catalog="HealthInformationSystem"
)
public class OrgUnitGroup  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -3294429286312734427L;
	private int orgUnitGroupId;
     private String name;
     private String uid;
     private String code;
     private String symbol;
     private Date lastUpdated;
     private Date created;
     private Integer userId;
     private String publicAccess;
     private Boolean disabled;
     private String shortName;

    public OrgUnitGroup() {
    }

	
    public OrgUnitGroup(int orgUnitGroupId, String name, String shortName) {
        this.orgUnitGroupId = orgUnitGroupId;
        this.name = name;
        this.shortName = shortName;
    }
    public OrgUnitGroup(int orgUnitGroupId, String name, String uid, String code, String symbol, Date lastUpdated, Date created, Integer userId, String publicAccess, Boolean disabled, String shortName) {
       this.orgUnitGroupId = orgUnitGroupId;
       this.name = name;
       this.uid = uid;
       this.code = code;
       this.symbol = symbol;
       this.lastUpdated = lastUpdated;
       this.created = created;
       this.userId = userId;
       this.publicAccess = publicAccess;
       this.disabled = disabled;
       this.shortName = shortName;
    }
   
     @Id 

    
    @Column(name="OrgUnitGroupID", unique=true, nullable=false)
    public int getOrgUnitGroupId() {
        return this.orgUnitGroupId;
    }
    
    public void setOrgUnitGroupId(int orgUnitGroupId) {
        this.orgUnitGroupId = orgUnitGroupId;
    }

    
    @Column(name="Name", nullable=false, length=160)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="UID", length=11)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }

    
    @Column(name="Code", length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="Symbol")
    public String getSymbol() {
        return this.symbol;
    }
    
    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdated", length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Created", length=10)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="UserID")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    
    @Column(name="PublicAccess", length=8)
    public String getPublicAccess() {
        return this.publicAccess;
    }
    
    public void setPublicAccess(String publicAccess) {
        this.publicAccess = publicAccess;
    }

    
    @Column(name="Disabled")
    public Boolean getDisabled() {
        return this.disabled;
    }
    
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    
    @Column(name="ShortName", nullable=false, length=50)
    public String getShortName() {
        return this.shortName;
    }
    
    public void setShortName(String shortName) {
        this.shortName = shortName;
    }




}


