package vn.com.daisy.organisation;
// Generated Oct 20, 2015 8:20:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrgUnitLevel generated by hbm2java
 */
@Entity
@Table(name="OrgUnitLevel"
    ,catalog="HealthInformationSystem"
)
public class OrgUnitLevel  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 3769363592514777602L;
	private int orgUnitLevelId;
     private int level;
     private String name;
     private String code;
     private String uid;
     private Date lastUpdated;
     private Date created;
     private Integer offLineLevels;

    public OrgUnitLevel() {
    }

	
    public OrgUnitLevel(int orgUnitLevelId, int level, String name) {
        this.orgUnitLevelId = orgUnitLevelId;
        this.level = level;
        this.name = name;
    }
    public OrgUnitLevel(int orgUnitLevelId, int level, String name, String code, String uid, Date lastUpdated, Date created, Integer offLineLevels) {
       this.orgUnitLevelId = orgUnitLevelId;
       this.level = level;
       this.name = name;
       this.code = code;
       this.uid = uid;
       this.lastUpdated = lastUpdated;
       this.created = created;
       this.offLineLevels = offLineLevels;
    }
   
     @Id 

    
    @Column(name="OrgUnitLevelID", unique=true, nullable=false)
    public int getOrgUnitLevelId() {
        return this.orgUnitLevelId;
    }
    
    public void setOrgUnitLevelId(int orgUnitLevelId) {
        this.orgUnitLevelId = orgUnitLevelId;
    }

    
    @Column(name="Level", nullable=false)
    public int getLevel() {
        return this.level;
    }
    
    public void setLevel(int level) {
        this.level = level;
    }

    
    @Column(name="Name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Code", length=50)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="UID", length=11)
    public String getUid() {
        return this.uid;
    }
    
    public void setUid(String uid) {
        this.uid = uid;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdated", length=19)
    public Date getLastUpdated() {
        return this.lastUpdated;
    }
    
    public void setLastUpdated(Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Created", length=19)
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }

    
    @Column(name="OffLineLevels")
    public Integer getOffLineLevels() {
        return this.offLineLevels;
    }
    
    public void setOffLineLevels(Integer offLineLevels) {
        this.offLineLevels = offLineLevels;
    }




}


