package vn.com.daisy.organisation;
// Generated Nov 22, 2015 4:59:23 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrgUnitGroupSetMember generated by hbm2java
 */
@Entity
@Table(name="OrgUnitGroupSetMember"
    ,catalog="HealthInformationSystem"
)
public class OrgUnitGroupSetMember  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 4549650176378255518L;
	private OrgUnitGroupSetMemberId id;

    public OrgUnitGroupSetMember() {
    }

    public OrgUnitGroupSetMember(OrgUnitGroupSetMemberId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="orgUnitGroupSetId", column=@Column(name="OrgUnitGroupSetID", nullable=false) ), 
        @AttributeOverride(name="orgUnitGroupId", column=@Column(name="OrgUnitGroupID", nullable=false) ) } )
    public OrgUnitGroupSetMemberId getId() {
        return this.id;
    }
    
    public void setId(OrgUnitGroupSetMemberId id) {
        this.id = id;
    }




}


