package vn.com.daisy.organisation;
// Generated Nov 22, 2015 4:59:23 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrgUnitGroupMembersId generated by hbm2java
 */
@Embeddable
public class OrgUnitGroupMembersId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -1720598162157673631L;
	private int orgUnitGroupId;
     private int organisationUnitId;

    public OrgUnitGroupMembersId() {
    }

    public OrgUnitGroupMembersId(int orgUnitGroupId, int organisationUnitId) {
       this.orgUnitGroupId = orgUnitGroupId;
       this.organisationUnitId = organisationUnitId;
    }
   


    @Column(name="OrgUnitGroupID", nullable=false)
    public int getOrgUnitGroupId() {
        return this.orgUnitGroupId;
    }
    
    public void setOrgUnitGroupId(int orgUnitGroupId) {
        this.orgUnitGroupId = orgUnitGroupId;
    }


    @Column(name="OrganisationUnitID", nullable=false)
    public int getOrganisationUnitId() {
        return this.organisationUnitId;
    }
    
    public void setOrganisationUnitId(int organisationUnitId) {
        this.organisationUnitId = organisationUnitId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrgUnitGroupMembersId) ) return false;
		 OrgUnitGroupMembersId castOther = ( OrgUnitGroupMembersId ) other; 
         
		 return (this.getOrgUnitGroupId()==castOther.getOrgUnitGroupId())
 && (this.getOrganisationUnitId()==castOther.getOrganisationUnitId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrgUnitGroupId();
         result = 37 * result + this.getOrganisationUnitId();
         return result;
   }   


}


