package vn.com.daisy.datavalue;
// Generated Oct 14, 2015 4:32:22 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DataValueId generated by hbm2java
 */
@Embeddable
public class DataValueId  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -6469395176824108387L;
	private int dataElementId;
     private int periodId;
     private int organitionUnitId;
     private int categoryOptionId;

    public DataValueId() {
    }

    public DataValueId(int dataElementId, int periodId, int organitionUnitId, int categoryOptionId) {
       this.dataElementId = dataElementId;
       this.periodId = periodId;
       this.organitionUnitId = organitionUnitId;
       this.categoryOptionId = categoryOptionId;
    }
   


    @Column(name="DataElementID", nullable=false)
    public int getDataElementId() {
        return this.dataElementId;
    }
    
    public void setDataElementId(int dataElementId) {
        this.dataElementId = dataElementId;
    }


    @Column(name="PeriodID", nullable=false)
    public int getPeriodId() {
        return this.periodId;
    }
    
    public void setPeriodId(int periodId) {
        this.periodId = periodId;
    }


    @Column(name="OrganitionUnitID", nullable=false)
    public int getOrganitionUnitId() {
        return this.organitionUnitId;
    }
    
    public void setOrganitionUnitId(int organitionUnitId) {
        this.organitionUnitId = organitionUnitId;
    }


    @Column(name="CategoryOptionID", nullable=false)
    public int getCategoryOptionId() {
        return this.categoryOptionId;
    }
    
    public void setCategoryOptionId(int categoryOptionId) {
        this.categoryOptionId = categoryOptionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DataValueId) ) return false;
		 DataValueId castOther = ( DataValueId ) other; 
         
		 return (this.getDataElementId()==castOther.getDataElementId())
 && (this.getPeriodId()==castOther.getPeriodId())
 && (this.getOrganitionUnitId()==castOther.getOrganitionUnitId())
 && (this.getCategoryOptionId()==castOther.getCategoryOptionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDataElementId();
         result = 37 * result + this.getPeriodId();
         result = 37 * result + this.getOrganitionUnitId();
         result = 37 * result + this.getCategoryOptionId();
         return result;
   }   


}


