package vn.com.daisy.datavalue;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DataValue generated by hbm2java
 */
@Entity
@Table(name="DataValue"
    ,catalog="HealthInformationSystem"
)
public class DataValue  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -4000202880966911373L;
	private DataValueId id;
     private String value;
     private Date createDate;
     private Date lastUpdate;
     private Integer userId;

    public DataValue() {
    }

	
    public DataValue(DataValueId id) {
        this.id = id;
    }
    public DataValue(DataValueId id, String value, Date createDate, Date lastUpdate, Integer userId) {
       this.id = id;
       this.value = value;
       this.createDate = createDate;
       this.lastUpdate = lastUpdate;
       this.userId = userId;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="dataElementId", column=@Column(name="DataElementID", nullable=false) ), 
        @AttributeOverride(name="periodId", column=@Column(name="PeriodID", nullable=false) ), 
        @AttributeOverride(name="organitionUnitId", column=@Column(name="OrganitionUnitID", nullable=false) ), 
        @AttributeOverride(name="categoryOptionId", column=@Column(name="CategoryOptionID", nullable=false) ) } )
    public DataValueId getId() {
        return this.id;
    }
    
    public void setId(DataValueId id) {
        this.id = id;
    }

    
    @Column(name="Value", length=50)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createDate", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LastUpdate", length=19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    
    @Column(name="UserID")
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }




}


