package vn.com.daisy.form;
// Generated Nov 20, 2015 1:15:12 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Form generated by hbm2java
 */
@Entity
@Table(name="Form"
    ,catalog="HealthInformationSystem"
)
public class Form  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = -8036007683145219585L;
	private int formId;
     private String name;
     private String htmlCode;
     private String style;
     private int format;

    public Form() {
    }

    public Form(int formId, String name, String htmlCode, String style, int format) {
       this.formId = formId;
       this.name = name;
       this.htmlCode = htmlCode;
       this.style = style;
       this.format = format;
    }
   
     @Id 

    
    @Column(name="FormID", unique=true, nullable=false)
    public int getFormId() {
        return this.formId;
    }
    
    public void setFormId(int formId) {
        this.formId = formId;
    }

    
    @Column(name="Name", nullable=false, length=160)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="HtmlCode", nullable=false)
    public String getHtmlCode() {
        return this.htmlCode;
    }
    
    public void setHtmlCode(String htmlCode) {
        this.htmlCode = htmlCode;
    }

    
    @Column(name="Style", nullable=false, length=40)
    public String getStyle() {
        return this.style;
    }
    
    public void setStyle(String style) {
        this.style = style;
    }

    
    @Column(name="Format", nullable=false)
    public int getFormat() {
        return this.format;
    }
    
    public void setFormat(int format) {
        this.format = format;
    }




}


